name: "Okteto Pipeline"
description: "Trigger you repository's okteto pipeline"
inputs:
  name: 
    description: 'The name of the pipeline'
    required: true
  namespace: 
    description: 'If present, the namespace scope for this action. If not specified, it will use the current context'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name }}
    - ${{ inputs.namespace }}
branding:
  color: 'green'
  icon: 'settings'